//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Novel.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Novel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ayla {
            get {
                object obj = ResourceManager.GetObject("Ayla", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ayla_icon {
            get {
                object obj = ResourceManager.GetObject("Ayla_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ayla_icon_Normal {
            get {
                object obj = ResourceManager.GetObject("Ayla_icon_Normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ayla_icon_Round {
            get {
                object obj = ResourceManager.GetObject("Ayla_icon_Round", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ayla_left {
            get {
                object obj = ResourceManager.GetObject("Ayla_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ayla_right {
            get {
                object obj = ResourceManager.GetObject("Ayla_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayla: Ayla wood go
        ///Ayla: Ayla go home, Ayla eat, Ayla sleep, Ayla marry Kino, Ayla happy
        ///Ayla: Ayla thank Crono, Ayla go back.
        /// </summary>
        internal static string AylaReply {
            get {
                return ResourceManager.GetString("AylaReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap background {
            get {
                object obj = ResourceManager.GetObject("background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ChronoType {
            get {
                object obj = ResourceManager.GetObject("ChronoType", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Crono {
            get {
                object obj = ResourceManager.GetObject("Crono", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Crono_icon {
            get {
                object obj = ResourceManager.GetObject("Crono_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Crono_icon_Normal {
            get {
                object obj = ResourceManager.GetObject("Crono_icon_Normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Crono_icon_Round {
            get {
                object obj = ResourceManager.GetObject("Crono_icon_Round", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Crono_left {
            get {
                object obj = ResourceManager.GetObject("Crono_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Crono_right {
            get {
                object obj = ResourceManager.GetObject("Crono_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crono: Hey Ayla, what you plan to do when we finish with Lavos?
        ///Crono: Haha, That`s great.
        /// </summary>
        internal static string CronoAylaReply {
            get {
                return ResourceManager.GetString("CronoAylaReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crono: Hey Frog, what you plan to do when we finish with Lavos?
        ///Crono: I am glad that you have forgiven yourself and can live your life without regrets.
        /// </summary>
        internal static string CronoFrogReply {
            get {
                return ResourceManager.GetString("CronoFrogReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crono: Hey Lucca, what you plan to do when we finish with Lavos?
        ///Crono: That&apos;s nice, I&apos;ll be looking for it.
        /// </summary>
        internal static string CronoLuccaReply {
            get {
                return ResourceManager.GetString("CronoLuccaReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crono: Hey Magus, what you plan to do when we finish with Lavos?
        ///Crono: I see, hope it&apos;ll be okay without Lavosthat screwed up your mother.
        /// </summary>
        internal static string CronoMagusReply {
            get {
                return ResourceManager.GetString("CronoMagusReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crono: Hey Marle, what you plan to do when we finish with Lavos?
        ///Crono: That&apos;s nice, I can&apos;t wait to see my mom again too.
        /// </summary>
        internal static string CronoMarleReply {
            get {
                return ResourceManager.GetString("CronoMarleReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crono: I&apos;ll go gather some wood for a campfire, who wants to come with me?.
        /// </summary>
        internal static string CronoReply {
            get {
                return ResourceManager.GetString("CronoReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crono: Hey Rob, what you plan to do when we finish with Lavos?
        ///Crono: I believe it will be good.
        /// </summary>
        internal static string CronoRoboReply {
            get {
                return ResourceManager.GetString("CronoRoboReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Frog {
            get {
                object obj = ResourceManager.GetObject("Frog", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Frog_icon {
            get {
                object obj = ResourceManager.GetObject("Frog_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Frog_icon_Normal {
            get {
                object obj = ResourceManager.GetObject("Frog_icon_Normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Frog_icon_Round {
            get {
                object obj = ResourceManager.GetObject("Frog_icon_Round", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Frog_left {
            get {
                object obj = ResourceManager.GetObject("Frog_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Frog_right {
            get {
                object obj = ResourceManager.GetObject("Frog_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frog: Let&apos;s go Crono
        ///Frog: I will return to my time and serve my kingdom as Cyrus did
        ///Frog: Thanks Crono, you became an amazing swordsman and let&apos;s go back we got what we came for.
        /// </summary>
        internal static string FrogReply {
            get {
                return ResourceManager.GetString("FrogReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Lucca {
            get {
                object obj = ResourceManager.GetObject("Lucca", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Lucca_icon {
            get {
                object obj = ResourceManager.GetObject("Lucca_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Lucca_icon_Normal {
            get {
                object obj = ResourceManager.GetObject("Lucca_icon_Normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Lucca_icon_Round {
            get {
                object obj = ResourceManager.GetObject("Lucca_icon_Round", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Lucca_left {
            get {
                object obj = ResourceManager.GetObject("Lucca_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Lucca_right {
            get {
                object obj = ResourceManager.GetObject("Lucca_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lucca: Let&apos;s go Crono
        ///Lucca: When we will return to our time, I will keep inventing stuff with my dad to help people 
        ///Lucca: Thanks Crono, hope I will get some from you with them and let&apos;s go back, we got what we needed.
        /// </summary>
        internal static string LuccaReply {
            get {
                return ResourceManager.GetString("LuccaReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Magus {
            get {
                object obj = ResourceManager.GetObject("Magus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Magus_icon {
            get {
                object obj = ResourceManager.GetObject("Magus_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Magus_icon_Normal {
            get {
                object obj = ResourceManager.GetObject("Magus_icon_Normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Magus_icon_Round {
            get {
                object obj = ResourceManager.GetObject("Magus_icon_Round", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Magus_left {
            get {
                object obj = ResourceManager.GetObject("Magus_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Magus_right {
            get {
                object obj = ResourceManager.GetObject("Magus_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magus: Let&apos;s go Crono
        ///Magus: I plan to return in my time and see what will happen to Kingdom of Zeal
        ///Magus: Thanks Crono, let&apos;s go back.
        /// </summary>
        internal static string MagusReply {
            get {
                return ResourceManager.GetString("MagusReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Marle {
            get {
                object obj = ResourceManager.GetObject("Marle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Marle_icon {
            get {
                object obj = ResourceManager.GetObject("Marle_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Marle_icon_Normal {
            get {
                object obj = ResourceManager.GetObject("Marle_icon_Normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Marle_icon_Round {
            get {
                object obj = ResourceManager.GetObject("Marle_icon_Round", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Marle_left {
            get {
                object obj = ResourceManager.GetObject("Marle_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Marle_right {
            get {
                object obj = ResourceManager.GetObject("Marle_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marle: Let&apos;s go Crono
        ///Marle: I want to talk with my father about our adventure and so much more, I need some time to think about it
        ///Marle: I don&apos;t know that you were a moms&apos; boy,  everyone is waiting, so let&apos;s go back.
        /// </summary>
        internal static string MarleReply {
            get {
                return ResourceManager.GetString("MarleReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pointer {
            get {
                object obj = ResourceManager.GetObject("pointer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Robo {
            get {
                object obj = ResourceManager.GetObject("Robo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Robo_icon {
            get {
                object obj = ResourceManager.GetObject("Robo_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Robo_icon_Normal {
            get {
                object obj = ResourceManager.GetObject("Robo_icon_Normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Robo_icon_Round {
            get {
                object obj = ResourceManager.GetObject("Robo_icon_Round", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Robo_left {
            get {
                object obj = ResourceManager.GetObject("Robo_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Robo_right {
            get {
                object obj = ResourceManager.GetObject("Robo_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robo: Let&apos;s go Crono
        ///Robo: I want to see how future will change after Lavos death
        ///Robo: Thanks Crono, you are saver of time and let&apos;s go back.
        /// </summary>
        internal static string RoboReply {
            get {
                return ResourceManager.GetString("RoboReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Scene_1 {
            get {
                object obj = ResourceManager.GetObject("Scene_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Scene_1_Normal {
            get {
                object obj = ResourceManager.GetObject("Scene_1_Normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Scene_2 {
            get {
                object obj = ResourceManager.GetObject("Scene_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Scene_2_Normal {
            get {
                object obj = ResourceManager.GetObject("Scene_2_Normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Title_Screen {
            get {
                object obj = ResourceManager.GetObject("Title_Screen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Title_Screen_Dark {
            get {
                object obj = ResourceManager.GetObject("Title_Screen_Dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Title_Screen_Normal {
            get {
                object obj = ResourceManager.GetObject("Title_Screen_Normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
